models/Topic.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the model class for table "{{%topic}}".
 *
 * @property int $id
 * @property string $title
 * @property int $userId
 * @property string $content
 * @property int $status
 * @property string $createAt
 * @property string $updateAt
 *
 * @property Comment[] $comments
 * @property User $user
 */
class Topic extends ActiveRecord
{

    const STATUS_NOT_ACCEPTED = 0;
    const STATUS_ACCEPTED = 1;
    const STATUS_REJECTED = 2;
    const STATUS_CLOSED = 3;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%topic}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createAt',
                'updatedAtAttribute' => 'updateAt',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userId', 'title', 'content'], 'required'],
            [['userId', 'status'], 'integer'],
            [['createAt', 'updateAt'], 'safe'],
            [['title', 'content'], 'string', 'max' => 255],
            [['userId'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['userId' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'userId' => 'User ID',
            'content' => 'Content',
            'status' => 'Status',
            'createAt' => 'Create At',
            'updateAt' => 'Update At',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['topicId' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'userId']);
    }
}

controllers/TopicController.php
<?php

namespace app\controllers;

use app\models\Comment;
use app\models\Like;
use app\models\Topic;
use Throwable;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\StaleObjectException;
use yii\web\Controller;
use yii\web\Response;

class TopicController extends Controller
{

    /**
     * List of Topics, only shown for Admin and Moderator
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Topic::find()
        ]);
        return $this->render('index', [
            'provider' => $dataProvider
        ]);
    }

    /**
     * Create new topic
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Topic();
        if ($model->load(Yii::$app->request->post())) {
            $model->status = Topic::STATUS_NOT_ACCEPTED;
            $model->userId = Yii::$app->getUser()->getId();
            if ($model->validate()) {
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', "Topic Created Successfully.");
                } else {
                    Yii::$app->session->setFlash('error', "Something Went Wrong.");
                }
                return $this->redirect([
                    '/site/index',
                ]);
            }
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * View topic details
     *
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        if ($topic = Topic::findOne($id)) {
            $comments = Comment::findAll([
                'topicId' => $id,
            ]);
            $model = new Comment();
            return $this->render('view', [
                'topic' => $topic,
                'comments' => $comments,
                'model' => $model
            ]);
        } else {
            Yii::$app->session->setFlash('error', "Topic Not Found.");
            return $this->redirect([
                '/site/index',
            ]);
        }
    }

    /**
     * Change topic status
     *
     * @param $id
     * @param $status
     * @return Response
     */
    public function actionStatus($id, $status)
    {
        if ($topic = Topic::findOne($id)) {
            $topic->status = $status;
            if ($topic->save()) {
                Yii::$app->session->setFlash('success', "Status Changed Successfully.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                '/topic/index',
            ]);
        } else {
            Yii::$app->session->setFlash('error', "Topic Not Found.");
            return $this->redirect([
                '/topic/index',
            ]);
        }
    }

    /**
     * Shows user's topics
     *
     * @return string
     */
    public function actionMy()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Topic::find()->where(['userId' => Yii::$app->user->getId()])
        ]);

        return $this->render('my', [
            'provider' => $dataProvider
        ]);
    }

    /**
     * @param $id
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        if ($topic = Topic::findOne($id)) {
            if ($topic->delete()) {
                Yii::$app->session->setFlash('success', "Topic Successfully Deleted.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
        } else {
            Yii::$app->session->setFlash('error', "Topic Not Found.");
        }

        $this->redirect([
            'topic/my'
        ]);
    }

    /**
     * Add new comment
     *
     * @param $topicId
     * @return Response
     */
    public function actionComment($topicId)
    {
        $model = new Comment();
        if ($model->load(Yii::$app->request->post())) {
            $model->userId = Yii::$app->user->getId();
            $model->topicId = $topicId;
            $model->parentId = null;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Added.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                'topic/view',
                'id' => $model->topicId,
            ]);
        }
    }

    /**
     * Like a comment
     *
     * @param $id
     * @param $type
     * @param $topic
     * @param $flag
     * @return Response
     * @throws Throwable
     */
    public function actionLike($id, $type, $topic, $flag)
    {
        if ($flag) {
            $like = new Like();
            $like->userId = Yii::$app->getUser()->getId();
            $like->commentId = $id;
            $like->type = $type;
            if ($like->save()) {
                return $this->redirect([
                    'topic/view',
                    'id' => $topic
                ]);
            }
        } else {
            $like = Like::findOne([
                'userId' => Yii::$app->getUser()->getId(),
                'commentId' => $id,
                'type' => $type
            ]);
            if ($like) {
                if ($like->delete()) {
                    return $this->redirect([
                        'topic/view',
                        'id' => $topic
                    ]);
                }
            }
            return $this->redirect([
                'topic/view',
                'id' => $topic
            ]);
        }
    }

    /**
     * Delete comment
     *
     * @param $id
     * @return Response
     * @throws StaleObjectException
     * @throws Throwable
     */
    public function actionDeleteComment($id)
    {
        if ($comment = Comment::findOne($id)) {
            if ($comment->delete()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Deleted.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
        } else {
            Yii::$app->session->setFlash('error', "Comment Not Found.");
        }
        return $this->redirect([
            'topic/view',
            'id' => $comment->topicId,
        ]);
    }

    /**
     * Reply to comment
     *
     * @param $id
     * @param $topicId
     * @return Response
     */
    public function actionReply($id, $topicId)
    {
        $model = new Comment();
        if ($model->load(Yii::$app->request->post())) {
            $model->userId = Yii::$app->user->getId();
            $model->topicId = $topicId;
            $model->parentId = $id;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Added.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                'topic/view',
                'id' => $model->topicId,
            ]);
        }
    }

    /**
     * Edit Comment
     *
     * @param $id
     * @return string|Response
     */
    public function actionEditComment($id)
    {
        $model = Comment::findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Edited.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                'topic/view',
                'id' => $model->topicId,
            ]);
        }
        return $this->render('edit', [
            'model' => $model
        ]);
    }


}

views/topic/create.php
<?php
/* @var $this View */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

$this->title = 'Create New Topic';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="topic-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to create new topic:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'create-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'title')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'content')->textarea() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'submit-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/topic/edit.php
<?php

/* @var $this View */

/* @var $model Comment */

use app\models\Comment;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

$this->title = "Edit Comment";
$this->params['breadcrumbs'][] = $this->title;
?>

<div>
    <?php $form = ActiveForm::begin(['action' => Url::to(['topic/edit-comment', 'id' => $model->id]), 'options' => ['method' => 'post']]) ?>
    <?= $form->field($model, 'content')->textInput(['placeholder' => "Enter Your Comment"])->label(false) ?>
    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'comment-button']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/topic/index.php
<?php
/* @var $this yii\web\View */
/* @var $provider ActiveDataProvider */
$this->title = 'Topics';
$this->params['breadcrumbs'][] = $this->title;

use app\models\Topic;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Html; ?>

    <h1><?= Html::encode($this->title) ?></h1>

<?= GridView::widget([
    'dataProvider' => $provider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'title',
        'content',
        [
            'attribute' => 'userId',
            'label' => 'User',
            'value' => function ($data) {
                return $data->user->name . ' ' . $data->user->family;
            },

        ],
        [
            'attribute' => 'status',
            'value' => function ($data) {
                switch ($data->status) {
                    case Topic::STATUS_NOT_ACCEPTED:
                        return 'Pending';
                    case Topic::STATUS_ACCEPTED:
                        return 'Accepted';
                    case Topic::STATUS_REJECTED:
                        return 'Rejected';
                    case Topic::STATUS_CLOSED:
                        return 'Closed';
                }
            },

        ],
        'createAt:datetime',
        'updateAt:datetime',
        [
            'label' => 'Change Status',
            'format' => 'raw',
            'value' => function ($data) {
                if ($data->status == Topic::STATUS_NOT_ACCEPTED)
                    return Html::a('Accept', ['topic/status', 'id' => $data->id, 'status' => Topic::STATUS_ACCEPTED]) . ' / ' .
                        Html::a('Reject', ['topic/status', 'id' => $data->id, 'status' => Topic::STATUS_REJECTED]);
                if ($data->status == Topic::STATUS_ACCEPTED)
                    return Html::a('Close', ['topic/status', 'id' => $data->id, 'status' => Topic::STATUS_CLOSED]);
                if ($data->status == Topic::STATUS_REJECTED)
                    return Html::a('Accept', ['topic/status', 'id' => $data->id, 'status' => Topic::STATUS_ACCEPTED]);
                if ($data->status == Topic::STATUS_CLOSED)
                    return Html::a('Open', ['topic/status', 'id' => $data->id, 'status' => Topic::STATUS_ACCEPTED]);
            },
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Actions',
            'headerOptions' => ['style' => 'color:#337ab7'],
            'template' => '{view}',
            'buttons' => [
                'view' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                        'title' => Yii::t('app', 'view'),
                    ]);
                },

            ],
            'urlCreator' => function ($action, $model, $key, $index) {
                if ($action === 'view') {
                    $url = 'view?id=' . $model->id;
                    return $url;
                }
            }
        ],
    ],
]);
?>

views/topic/my.php
<?php
/* @var $this yii\web\View */
/* @var $provider ActiveDataProvider */
$this->title = 'My Topics';
$this->params['breadcrumbs'][] = $this->title;

use app\models\Topic;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\web\View; ?>

    <h1><?= Html::encode($this->title) ?></h1>

<?= GridView::widget([
    'dataProvider' => $provider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'title',
        'content',
        [
            'attribute' => 'userId',
            'label' => 'User',
            'value' => function ($data) {
                return $data->user->name . ' ' . $data->user->family;
            },

        ],
        [
            'attribute' => 'status',
            'value' => function ($data) {
                switch ($data->status) {
                    case Topic::STATUS_NOT_ACCEPTED:
                        return 'Pending';
                    case Topic::STATUS_ACCEPTED:
                        return 'Accepted';
                    case Topic::STATUS_REJECTED:
                        return 'Rejected';
                    case Topic::STATUS_CLOSED:
                        return 'Closed';
                }
            },

        ],
        'createAt:datetime',
        'updateAt:datetime',
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Actions',
            'headerOptions' => ['style' => 'color:#337ab7'],
            'template' => '{view}{delete}',
            'buttons' => [
                'view' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                        'title' => Yii::t('app', 'view'),
                    ]);
                },
                'delete' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                        'title' => Yii::t('app', 'delete'),
                    ]);
                }

            ],
            'urlCreator' => function ($action, $model, $key, $index) {
                if ($action === 'view') {
                    $url = 'view?id=' . $model->id;
                    return $url;
                }
                if ($action === 'delete') {
                    $url ='delete?id='.$model->id;
                    return $url;
                }
            }
        ],
    ],
]);
?>

views/topic/view.php
<?php
/* @var $this View */
/* @var $topic Topic */
/* @var $comments Comment[] */

/* @var $model Comment */

use app\models\Comment;
use app\models\Like;
use app\models\Topic;
use app\models\User;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

$this->title = $topic->title;
$this->params['breadcrumbs'][] = $this->title;

$userId = Yii::$app->getUser()->id;
?>


<div class="view-topic">
    <h1 style="margin-bottom: 20px"><?= Html::encode($this->title) ?></h1>
    <p style="border: 1px #d0f3ff; background: #e9f4ff; font-size: medium; margin-bottom: 20px;"><?= $topic->content ?></p>
    <div class="form-group">
        <div class="col-md-4"
             style="font-size: small; margin-bottom: 20px"><?= $topic->user->name . ' ' . $topic->user->family ?></div>
        <? if ($topic->userId == Yii::$app->getUser()->getId()): ?>
            <? if ($topic->status == Topic::STATUS_NOT_ACCEPTED): ?>
                <div class="col-md-4" style="font-size: small">Status: Pending</div>
            <? elseif ($topic->status == Topic::STATUS_ACCEPTED): ?>
                <div class="col-md-4" style="font-size: small">Status: Accepted</div>
            <? elseif ($topic->status == Topic::STATUS_REJECTED): ?>
                <div class="col-md-4" style="font-size: small">Status: Rejected</div>
            <? endif; ?>
        <? endif; ?>
        <? if ($topic->status == Topic::STATUS_CLOSED): ?>
            <div class="col-md-4" style="font-size: small">Status: Closed</div>
        <? endif; ?>
        <div class="col-md-4" style="font-size: small">Created At: <?= $topic->createAt ?></div>
    </div>

    <? if (!Yii::$app->getUser()->isGuest): ?>
        <div>
            <?php $form = ActiveForm::begin(['action' => Url::to(['topic/comment', 'topicId' => $topic->id]), 'options' => ['method' => 'post']]) ?>
            <?= $form->field($model, 'content')->textInput(['placeholder' => "Enter Your Comment"])->label(false) ?>
            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'comment-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    <? endif; ?>

    <? if ($comments != null): ?>
        <? foreach ($comments as $comment): ?>
            <div style="font-size: medium; margin-bottom: 10px; padding: 8px; border: 1px solid gray; border-radius: 5px;">
                <h4><?= $comment->user->name ?> :</h4>
                <h5><?= $comment->user->username ?></h5>
                <p>
                    <?= $comment->content ?>
                </p>
                <p style="font-size: xx-small">
                    <? if (!$comment->parentId == null): ?>
                        Replied to comment <?= $comment->parentId ?>
                    <? endif; ?>
                    Comment id: <?= $comment->id ?>
                </p>
            </div>
            <? if ($comment->userLiked(Like::TYPE_LIKE)): ?>
                <?= Html::a('Unlike', ['topic/like', 'id' => $comment->id, 'type' => Like::TYPE_LIKE, 'topic' => $topic->id, 'flag' => false]); ?>
            <? else: ?>
                <?= Html::a('Like', ['topic/like', 'id' => $comment->id, 'type' => Like::TYPE_LIKE, 'topic' => $topic->id, 'flag' => true]); ?>
            <? endif; ?>
            <?= $comment->getLikeCount(Like::TYPE_LIKE) ?>
            <? if ($comment->userLiked(Like::TYPE_DISLIKE)): ?>
                <?= Html::a('UnDislike', ['topic/like', 'id' => $comment->id, 'type' => Like::TYPE_DISLIKE, 'topic' => $topic->id, 'flag' => false]); ?>
            <? else: ?>
                <?= Html::a('Dislike', ['topic/like', 'id' => $comment->id, 'type' => Like::TYPE_DISLIKE, 'topic' => $topic->id, 'flag' => true]); ?>
            <? endif; ?>
            <?= $comment->getLikeCount(Like::TYPE_DISLIKE) ?>
            <? if (User::isAdmin($userId) or User::isModerator($userId) or $comment->userId == $userId): ?>
                <?= Html::a('Delete', ['topic/delete-comment', 'id' => $comment->id]); ?>
            <? endif; ?>
            <? if ($comment->userId == $userId): ?>
                <?= Html::a('Edit', ['topic/edit-comment', 'id' => $comment->id]); ?>
            <? endif; ?>
            <div style="margin-left: 20px;margin-top: 10px;">
                <?php $form = ActiveForm::begin(['action' => Url::to(['topic/reply', 'id' => $comment->id, 'topicId' => $topic->id]), 'options' => ['method' => 'post']]) ?>
                <?= $form->field($model, 'content')->textInput(['placeholder' => "Enter Your Comment"])->label(false) ?>
                <div class="form-group">
                    <?= Html::submitButton('Reply', ['class' => 'btn btn-primary', 'name' => 'comment-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>

        <? endforeach; ?>
    <? endif; ?>


</div>