controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\SignUpForm;
use app\models\Topic;
use app\models\User;
use Yii;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     * @throws Exception
     */
    public function actionIndex()
    {
        if (!$admin = User::findOne(['type' => User::TYPE_ADMIN])) {
            $admin = new User();
            $admin->name = "admin";
            $admin->family = "";
            $admin->username = "admin";
            $admin->password = Yii::$app->getSecurity()->generatePasswordHash("adminadmin");
            $admin->status = User::STATUS_NOT_BLOCKED;
            $admin->type = User::TYPE_ADMIN;
            if (!$admin->save()) {
                Yii::$app->session->setFlash('error', "Couldn't Add Admin.");
            }
        }
        $dataProvider = new ActiveDataProvider([
            'query' => Topic::find()->where(['status' => Topic::STATUS_ACCEPTED])
        ]);
        return $this->render('index', [
            'provider' => $dataProvider
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goHome();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * SingUp action
     *
     * @return string|Response
     * @throws Exception
     */
    public function actionSignup()
    {
        $model = new SignUpForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->singUp()) {
                Yii::$app->session->setFlash('success', "You Registered Successfully.");
                return $this->redirect([
                    '/site/index',
                ]);
            }
        }
        return $this->render('signup', [
            'model' => $model
        ]);
    }

    /**
     * Shows all users to Admin
     * @return string
     */
    public function actionUsers()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find()->where(['<>', 'type', User::TYPE_ADMIN])
        ]);
        return $this->render('users', [
            'provider' => $dataProvider
        ]);
    }

    /**
     * Promotes or demotes users
     * @param $id
     * @return Response
     */
    public function actionPromote($id)
    {
        if ($user = User::findOne($id)) {
            if ($user->type == User::TYPE_MODERATOR) {
                $user->type = User::TYPE_USER;
            } else {
                $user->type = User::TYPE_MODERATOR;
            }
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            Yii::$app->session->setFlash('success', "Success.");
            return $this->redirect([
                'site/users'
            ]);
        } else {
            Yii::$app->session->setFlash('error', "Couldn't Find User.");
            return $this->redirect([
                'site/users'
            ]);
        }
    }

    /**
     * Block or unblock user
     *
     * @param $id
     * @return Response
     */
    public function actionBlock($id)
    {
        if ($user = User::findOne($id)) {
            if ($user->status == User::STATUS_NOT_BLOCKED) {
                $user->status = User::STATUS_BLOCKED;
            } else {
                $user->status = User::STATUS_NOT_BLOCKED;
            }
            if (!$user->save()) {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            Yii::$app->session->setFlash('success', "Success.");
            return $this->redirect([
                'site/users'
            ]);
        } else {
            Yii::$app->session->setFlash('error', "Couldn't Find User.");
            return $this->redirect([
                'site/users'
            ]);
        }
    }

}

controllers/TopicController.php
<?php

namespace app\controllers;

use app\models\Comment;
use app\models\Like;
use app\models\Topic;
use Throwable;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\StaleObjectException;
use yii\web\Controller;
use yii\web\Response;

class TopicController extends Controller
{

    /**
     * List of Topics, only shown for Admin and Moderator
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Topic::find()
        ]);
        return $this->render('index', [
            'provider' => $dataProvider
        ]);
    }

    /**
     * Create new topic
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Topic();
        if ($model->load(Yii::$app->request->post())) {
            $model->status = Topic::STATUS_NOT_ACCEPTED;
            $model->userId = Yii::$app->getUser()->getId();
            if ($model->validate()) {
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', "Topic Created Successfully.");
                } else {
                    Yii::$app->session->setFlash('error', "Something Went Wrong.");
                }
                return $this->redirect([
                    '/site/index',
                ]);
            }
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * View topic details
     *
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        if ($topic = Topic::findOne($id)) {
            $comments = Comment::findAll([
                'topicId' => $id,
            ]);
            $model = new Comment();
            return $this->render('view', [
                'topic' => $topic,
                'comments' => $comments,
                'model' => $model
            ]);
        } else {
            Yii::$app->session->setFlash('error', "Topic Not Found.");
            return $this->redirect([
                '/site/index',
            ]);
        }
    }

    /**
     * Change topic status
     *
     * @param $id
     * @param $status
     * @return Response
     */
    public function actionStatus($id, $status)
    {
        if ($topic = Topic::findOne($id)) {
            $topic->status = $status;
            if ($topic->save()) {
                Yii::$app->session->setFlash('success', "Status Changed Successfully.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                '/topic/index',
            ]);
        } else {
            Yii::$app->session->setFlash('error', "Topic Not Found.");
            return $this->redirect([
                '/topic/index',
            ]);
        }
    }

    /**
     * Shows user's topics
     *
     * @return string
     */
    public function actionMy()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Topic::find()->where(['userId' => Yii::$app->user->getId()])
        ]);

        return $this->render('my', [
            'provider' => $dataProvider
        ]);
    }

    /**
     * @param $id
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        if ($topic = Topic::findOne($id)) {
            if ($topic->delete()) {
                Yii::$app->session->setFlash('success', "Topic Successfully Deleted.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
        } else {
            Yii::$app->session->setFlash('error', "Topic Not Found.");
        }

        $this->redirect([
            'topic/my'
        ]);
    }

    /**
     * Add new comment
     *
     * @param $topicId
     * @return Response
     */
    public function actionComment($topicId)
    {
        $model = new Comment();
        if ($model->load(Yii::$app->request->post())) {
            $model->userId = Yii::$app->user->getId();
            $model->topicId = $topicId;
            $model->parentId = null;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Added.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                'topic/view',
                'id' => $model->topicId,
            ]);
        }
    }

    /**
     * Like a comment
     *
     * @param $id
     * @param $type
     * @param $topic
     * @param $flag
     * @return Response
     * @throws Throwable
     */
    public function actionLike($id, $type, $topic, $flag)
    {
        if ($flag) {
            $like = new Like();
            $like->userId = Yii::$app->getUser()->getId();
            $like->commentId = $id;
            $like->type = $type;
            if ($like->save()) {
                return $this->redirect([
                    'topic/view',
                    'id' => $topic
                ]);
            }
        } else {
            $like = Like::findOne([
                'userId' => Yii::$app->getUser()->getId(),
                'commentId' => $id,
                'type' => $type
            ]);
            if ($like) {
                if ($like->delete()) {
                    return $this->redirect([
                        'topic/view',
                        'id' => $topic
                    ]);
                }
            }
            return $this->redirect([
                'topic/view',
                'id' => $topic
            ]);
        }
    }

    /**
     * Delete comment
     *
     * @param $id
     * @return Response
     * @throws StaleObjectException
     * @throws Throwable
     */
    public function actionDeleteComment($id)
    {
        if ($comment = Comment::findOne($id)) {
            if ($comment->delete()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Deleted.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
        } else {
            Yii::$app->session->setFlash('error', "Comment Not Found.");
        }
        return $this->redirect([
            'topic/view',
            'id' => $comment->topicId,
        ]);
    }

    /**
     * Reply to comment
     *
     * @param $id
     * @param $topicId
     * @return Response
     */
    public function actionReply($id, $topicId)
    {
        $model = new Comment();
        if ($model->load(Yii::$app->request->post())) {
            $model->userId = Yii::$app->user->getId();
            $model->topicId = $topicId;
            $model->parentId = $id;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Added.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                'topic/view',
                'id' => $model->topicId,
            ]);
        }
    }

    /**
     * Edit Comment
     *
     * @param $id
     * @return string|Response
     */
    public function actionEditComment($id)
    {
        $model = Comment::findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', "Comment Successfully Edited.");
            } else {
                Yii::$app->session->setFlash('error', "Something Went Wrong.");
            }
            return $this->redirect([
                'topic/view',
                'id' => $model->topicId,
            ]);
        }
        return $this->render('edit', [
            'model' => $model
        ]);
    }


}

views/site/_list_item.php
<?php
/* @var $model Topic */

use app\models\Topic;
use yii\helpers\Html;

?>

<div class="list-item col-sm-12" data-key="<?= $model['id'] ?>" style="border:1px solid gray; margin-bottom: 15px; border-radius: 10px;">
    <h3><?= Html::a(Html::encode($model['title']), ['topic/view', 'id' => $model->id]); ?></h3>
    <p><?= Html::encode($model['content']); ?></p>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $provider ActiveDataProvider */
/* @var $comment Comment */

$this->title = 'Forum';

use app\models\Comment;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\widgets\ListView; ?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Forum</h1>

        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

        <? if (!Yii::$app->getUser()->isGuest): ?>
            <p><?= Html::a('Create new Topic', ['topic/create'], ['class' => 'btn btn-lg btn-success']) ?></p>
        <? endif; ?>
    </div>

    <div>
        <?=
        ListView::widget([
            'dataProvider' => $provider,
            'options' => [
                'tag' => 'div',
                'class' => 'bordered bgblack',
                'id' => 'list-wrapper',
            ],
            'layout' => "{pager}\n{items}\n{summary}",
            'itemView' => function ($model, $key, $index, $widget) {
                $itemContent = $this->render('_list_item', ['model' => $model]);
                return $itemContent;
            },
            'pager' => [
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last',
                'maxButtonCount' => 4,
                'options' => [
                    'class' => 'pagination col-xs-12'
                ]
            ]
        ]);
        ?>
    </div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
    
</div>

views/site/signup.php
<?php
/* @var $this View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model SignUpForm */

use app\models\SignUpForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

$this->title = 'Sign Up';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to sign up:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'sigup-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'family')->textInput() ?>

    <?= $form->field($model, 'username')->textInput() ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Sign Up', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/users.php
<?php
/* @var $this View */

/* @var $provider ActiveDataProvider */

use app\models\User;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\web\View;

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
$user = User::findOne(Yii::$app->user->getId());
?>

<h1><?= Html::encode($this->title) ?></h1>
<? if ($user): ?>
    <? if ($user->type == User::TYPE_ADMIN): ?>
        <?= GridView::widget([
            'dataProvider' => $provider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'name',
                'family',
                'username',
                [
                    'attribute' => 'type',
                    'value' => function ($data) {
                        if ($data->type == User::TYPE_USER)
                            return 'User';
                        return 'Moderator';
                    },

                ],
                'createAt:datetime',
                'updateAt:datetime',
                [
                    'label' => 'Promotion',
                    'format' => 'raw',
                    'value' => function ($data) {
                        if ($data->type == User::TYPE_MODERATOR)
                            return Html::a('Demote', ['site/promote', 'id' => $data->id]);
                        return Html::a('Promote', ['site/promote', 'id' => $data->id]);
                    },
                ],
                [
                    'label' => 'Block',
                    'format' => 'raw',
                    'value' => function ($data) {
                        if ($data->status == User::STATUS_NOT_BLOCKED)
                            return Html::a('Block', ['site/block', 'id' => $data->id]);
                        return Html::a('UnBlock', ['site/block', 'id' => $data->id]);
                    },
                ],
            ],
        ]);
        ?>
    <? elseif ($user->type == User::TYPE_MODERATOR): ?>
        <?= GridView::widget([
            'dataProvider' => $provider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'name',
                'family',
                'username',
                [
                    'attribute' => 'type',
                    'value' => function ($data) {
                        if ($data->type == User::TYPE_USER)
                            return 'User';
                        return 'Moderator';
                    },

                ],
                'createAt:datetime',
                'updateAt:datetime',
                [
                    'label' => 'Block',
                    'format' => 'raw',
                    'value' => function ($data) {
                        if ($data->status == User::STATUS_NOT_BLOCKED)
                            return Html::a('Block', ['site/block', 'id' => $data->id]);
                        return Html::a('UnBlock', ['site/block', 'id' => $data->id]);
                    },
                ],
            ],
        ]);
        ?>
    <? endif; ?>
<? endif; ?>